version: '3.3'
services:
  ifg-postgresql:
    image: postgres:15.1
    container_name: jpa-sandbox-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jpa-sandbox
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
