spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa-sandbox
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: sandbox

  flyway:
    default-schema: sandbox

